### ISSUE TITLE
[BUG] Cartographer Villager crashes server

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/RealisticWorldGenerator-Api#10]
**Describe the bug**

The server starts suffering when you try to buy some maps from the cartograther villager

**To Reproduce**

1. Create RWG world
2. Find a village
3. Rightclick a Cartograther Villager
4. See the server suffering

**Expected behavior**

The Villager UI opens

**Server:**

 - Software: Spigot
 - Server Version: 1.16.5
 - Plugin Version: 4.34.8
 - Java Version: 16

**Comment by YellowPhoenix18** [comment]
Migrated issue to https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/9
