### ISSUE TITLE
[FEATURE] Add vanilla structures

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/RealisticWorldGenerator-Api#11]
**Is your feature request related to a problem? Please describe.**

Adding all vanilla structures in the default configurations of RWG would be great as players are missing some of them and not all user want to add them on their own... Probably because they're too lazy x)

**Describe the solution you'd like**

Adding missing vanilla structures
- [ ] Ruined Portal
- [ ] Ocean Temple
- [ ] Igloo
- [ ] Geode

**Comment by YellowPhoenix18** [comment]
Migrated issue to https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/14
