### ISSUE TITLE
[FEATURE] Round world borders

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/RealisticWorldGenerator-Api#13]
**Is your feature request related to a problem? Please describe.**

Some plate worlds would be great, as this would prove that Minecraft's world is flat

**Describe the solution you'd like**

A round border option for our world border

**Comment by YellowPhoenix18** [comment]
Migrated issue to https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/12
