### ISSUE TITLE
[FEATURE]  Spawning schematics based on a function or script

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/RealisticWorldGenerator-Api#15]
**Describe the solution you'd like**

Calculate the position of a schematic based on a function or script made by the user.<br>
This could be great for people who really want to enhance some schematic spawning

**Comment by YellowPhoenix18** [comment]
Migrated request to https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/1
