### ISSUE TITLE
[FEATURE] Biomes from Image

### ISSUE THREAD

**Issue by Lauriichan** [SourceWriters/RealisticWorldGenerator-Api#17]
**Describe the solution you'd like**

It would be interesting to see what people would do if they could draw their biomes onto an image and RWG uses them like that.

Sadly the possibilities of version 4 are quite limited in this case as there are no per biome noises and the ocean is based on noise which means that using Biomes from Image would cause no oceans to spawn

**Comment by YellowPhoenix18** [comment]
This issue was migrated to: https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/5
