### ISSUE TITLE
Trees spawn without base block.

### ISSUE THREAD

**Issue by LordVZlomka** [SourceWriters/RealisticWorldGenerator-Api#2]
Server: paper 1.16.5
Plugin version: 4.34.7
Description: When using saplings some trees spawn without the base block.
![image](https://user-images.githubusercontent.com/71541816/134301800-3aeaef83-4e21-4911-827a-b2d45bbac52d.png)
![image](https://user-images.githubusercontent.com/71541816/134301818-9bad1d61-a7e2-4809-8b7c-7cccff6b1597.png)
![image](https://user-images.githubusercontent.com/71541816/134301836-68988719-c40d-4e68-b2d0-c135b97ee119.png)

**Comment by Lauriichan** [comment]
This is not a bug, the only problem there is that the save position of some schematics seem to be set wrong.
You could edit those schematics by resaving them but there is no other "fix" for that then editing the schematics.
If we have the time we'll maybe update them in the future.
You could also just remove them from the trees list and use other ones.
The ones that have a wrong position are (as far as I've tested):
- OAK_TREE_3
- BIRCH_TREE_3
- BIRCH_TREE_4
