### ISSUE TITLE
Forge Compability

### ISSUE THREAD

**Issue by FranklinMCA** [SourceWriters/RealisticWorldGenerator-Api#22]
Here is my question. 
Does this plugin work on modded servers? 
I'm thinking mainly about ores and blocks from other mods.

Thanks for your answer!

**Comment by Lauriichan** [comment]
1. 
![image](https://user-images.githubusercontent.com/41839265/142503501-98215e47-4842-4238-9b3f-9310b407a7e0.png)

2. No, this is a bukkit plugin, not a mod for forge or any other things
