### ISSUE TITLE
[FEATURE] Adding multiple loottables to a schematic

### ISSUE THREAD

**Issue by lmoffat25** [SourceWriters/RealisticWorldGenerator-Api#29]
**Is your feature request related to a problem? Please describe.**
I would like my schematic to have different loot when it generates multiple times. So that every instance of my schematic feels different for the player, and keeps him interested in exploring. 

**Describe the solution you'd like**
When we create a chest with your plugin, we can "use" them on a schematic. Give the possibility to "use" multiple chests on a single schematics, and pick from them when the chematic is generated. I would like a given schematic (eg. a house), to generate once with chest A and a second time with chest B.

**Describe alternatives you've considered**
A working solution to this is to create 5 schematics of the same structure, with the only thing changing being the chest and its content. But that makes it very hard to maintain, and adds a huge amount of work.

**Additional context**
I have tried using Lootin, which is an improvment and lets you customize chest per chest. But once that chest is set, there is no way of randomising it. If the player stumbles uppon the same structure twice, he'll get the exact same loot again.

Thank you very much for your work, have a nice day.

**Comment by Lauriichan** [comment]
This is not something which we plan to do in future as creating multiple schematics can achieve the same thing.

**Comment by YellowPhoenix18** [comment]
This issue was migrated to https://votefeatures.com/project/sourcewriters/realisticworldgenerator/featurerequest/10
