### ISSUE TITLE
RealisticWorldGenerator gets stuck on enabling... 

### ISSUE THREAD

**Issue by mauxillarie** [SourceWriters/RealisticWorldGenerator-Api#4]
So I tried loading the plugin, but the console freezes and won't get past loading RealisticWorldGenerator...
[sample.txt](https://github.com/SourceWriters/RealisticWorldGenerator-Api/files/7274254/sample.txt)
It doesn't get past that.

**Comment by YellowPhoenix18** [comment]
I see no error nor any other problem. 3.8.6 boots fine on multiple other systems and also appears in our stats. Please delete all folders created by RWG and make sure to use a legit version.

**Comment by mauxillarie** [comment]
I am using a legitimate version, I bought the plugin on Saturday, and have the receipt for it too
<img width="847" alt="Screen Shot 2021-10-05 at 7 18 32 PM" src="https://user-images.githubusercontent.com/19752102/136121240-e73d5527-66b4-427f-a64b-139ddc71beaf.png">
.

**Comment by mauxillarie** [comment]
I did delete RWG folders as well, and that's still what happens/

**Comment by YellowPhoenix18** [comment]
Is it possible, that you have no connection at all to syntaxphoenix.com? Schematics and other stuff needs to get downloaded. Timeout is after around 30 seconds.

**Comment by mauxillarie** [comment]
How would I be able to troubleshoot that?

In the _YellowPhoenix18Stats_ -> **config.yml**, enabled: true

**Comment by YellowPhoenix18** [comment]
YellowPhoenix18-Stats is just the stats-system. If you have a Linux-machine you can simply ping the service with "ping antipiracy.syntaxphoenix.com" .

If you have no access may ask your hoster

**Comment by mauxillarie** [comment]
The server is being hosted locally on macOs Monterey. Here is the Terminal:

`Last login: Wed Oct  6 01:04:18 on ttys000
maux@MacBook-Pro ~ % ping antipiracy.syntaxphoenix.com
PING antipiracy.syntaxphoenix.com (45.135.203.22): 56 data bytes
64 bytes from 45.135.203.22: icmp_seq=0 ttl=29 time=152.984 ms
64 bytes from 45.135.203.22: icmp_seq=1 ttl=29 time=145.187 ms
64 bytes from 45.135.203.22: icmp_seq=2 ttl=29 time=135.552 ms
64 bytes from 45.135.203.22: icmp_seq=3 ttl=29 time=133.792 ms
64 bytes from 45.135.203.22: icmp_seq=4 ttl=29 time=137.515 ms
64 bytes from 45.135.203.22: icmp_seq=5 ttl=29 time=141.683 ms
64 bytes from 45.135.203.22: icmp_seq=6 ttl=29 time=140.356 ms
64 bytes from 45.135.203.22: icmp_seq=7 ttl=29 time=136.393 ms
64 bytes from 45.135.203.22: icmp_seq=8 ttl=29 time=134.715 ms
64 bytes from 45.135.203.22: icmp_seq=9 ttl=29 time=134.066 ms
64 bytes from 45.135.203.22: icmp_seq=10 ttl=29 time=135.598 ms
64 bytes from 45.135.203.22: icmp_seq=11 ttl=29 time=136.179 ms
64 bytes from 45.135.203.22: icmp_seq=12 ttl=29 time=144.921 ms
64 bytes from 45.135.203.22: icmp_seq=13 ttl=29 time=138.369 ms
64 bytes from 45.135.203.22: icmp_seq=14 ttl=29 time=142.982 ms
64 bytes from 45.135.203.22: icmp_seq=15 ttl=29 time=135.177 ms
64 bytes from 45.135.203.22: icmp_seq=16 ttl=29 time=134.424 ms
64 bytes from 45.135.203.22: icmp_seq=17 ttl=29 time=148.680 ms
64 bytes from 45.135.203.22: icmp_seq=18 ttl=29 time=133.004 ms
64 bytes from 45.135.203.22: icmp_seq=19 ttl=29 time=138.805 ms
64 bytes from 45.135.203.22: icmp_seq=20 ttl=29 time=132.846 ms
64 bytes from 45.135.203.22: icmp_seq=21 ttl=29 time=134.346 ms
64 bytes from 45.135.203.22: icmp_seq=22 ttl=29 time=135.193 ms
64 bytes from 45.135.203.22: icmp_seq=23 ttl=29 time=145.591 ms
64 bytes from 45.135.203.22: icmp_seq=24 ttl=29 time=138.116 ms
64 bytes from 45.135.203.22: icmp_seq=25 ttl=29 time=137.765 ms
64 bytes from 45.135.203.22: icmp_seq=26 ttl=29 time=142.918 ms
64 bytes from 45.135.203.22: icmp_seq=27 ttl=29 time=139.199 ms
64 bytes from 45.135.203.22: icmp_seq=28 ttl=29 time=146.582 ms
64 bytes from 45.135.203.22: icmp_seq=29 ttl=29 time=137.028 ms
64 bytes from 45.135.203.22: icmp_seq=30 ttl=29 time=135.717 ms
64 bytes from 45.135.203.22: icmp_seq=31 ttl=29 time=140.092 ms
64 bytes from 45.135.203.22: icmp_seq=32 ttl=29 time=132.575 ms
64 bytes from 45.135.203.22: icmp_seq=33 ttl=29 time=132.178 ms
64 bytes from 45.135.203.22: icmp_seq=34 ttl=29 time=136.791 ms
64 bytes from 45.135.203.22: icmp_seq=35 ttl=29 time=136.994 ms
64 bytes from 45.135.203.22: icmp_seq=36 ttl=29 time=139.438 ms
64 bytes from 45.135.203.22: icmp_seq=37 ttl=29 time=134.217 ms
64 bytes from 45.135.203.22: icmp_seq=38 ttl=29 time=130.777 ms
64 bytes from 45.135.203.22: icmp_seq=39 ttl=29 time=133.970 ms
64 bytes from 45.135.203.22: icmp_seq=40 ttl=29 time=138.804 ms
64 bytes from 45.135.203.22: icmp_seq=41 ttl=29 time=134.852 ms
64 bytes from 45.135.203.22: icmp_seq=42 ttl=29 time=131.841 ms
64 bytes from 45.135.203.22: icmp_seq=43 ttl=29 time=135.222 ms
64 bytes from 45.135.203.22: icmp_seq=44 ttl=29 time=134.040 ms
64 bytes from 45.135.203.22: icmp_seq=45 ttl=29 time=134.363 ms
64 bytes from 45.135.203.22: icmp_seq=46 ttl=29 time=134.103 ms
64 bytes from 45.135.203.22: icmp_seq=47 ttl=29 time=132.014 ms
64 bytes from 45.135.203.22: icmp_seq=48 ttl=29 time=136.361 ms
64 bytes from 45.135.203.22: icmp_seq=49 ttl=29 time=146.349 ms
64 bytes from 45.135.203.22: icmp_seq=50 ttl=29 time=137.083 ms
64 bytes from 45.135.203.22: icmp_seq=51 ttl=29 time=141.054 ms
64 bytes from 45.135.203.22: icmp_seq=52 ttl=29 time=134.676 ms
64 bytes from 45.135.203.22: icmp_seq=53 ttl=29 time=135.053 ms
64 bytes from 45.135.203.22: icmp_seq=54 ttl=29 time=138.589 ms
64 bytes from 45.135.203.22: icmp_seq=55 ttl=29 time=135.557 ms
64 bytes from 45.135.203.22: icmp_seq=56 ttl=29 time=132.863 ms
64 bytes from 45.135.203.22: icmp_seq=57 ttl=29 time=138.470 ms
64 bytes from 45.135.203.22: icmp_seq=58 ttl=29 time=141.193 ms
64 bytes from 45.135.203.22: icmp_seq=59 ttl=29 time=143.687 ms
64 bytes from 45.135.203.22: icmp_seq=60 ttl=29 time=136.568 ms
64 bytes from 45.135.203.22: icmp_seq=61 ttl=29 time=137.447 ms
`

**Comment by YellowPhoenix18** [comment]
Seems fine so far.
The times are not phenomenal, but also not bad.

Do you maybe use a very new Java-Edition like Java 16?

Have you the option to test RWG also on another system?

**Comment by mauxillarie** [comment]
I only have Mac; and I'm on Java 8:

> Last login: Fri Oct  8 14:02:00 on ttys000
maux@MacBook-Pro ~ % java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment Corretto-8.282.08.1 (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM Corretto-8.282.08.1 (build 25.282-b08, mixed mode)
maux@MacBook-Pro ~ %
